### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by ChadDa3mon** [NTTS-Innovation/GetCTS#1]
Would be nice if this wasn't case sensitive. 

Service level: CTS-S
/srv/docker/cts/data is not mounted. Please make sure to mount this path to a high performance NVMe disk
  with sufficent amount of free space for the calculated amount of recorded network traffic
Do you want this installer to try to find a partition to format for you? Type YES or NO: **yes**
Do you want this installer to try to find a partition to format for you? Type YES or NO: **YES**

**Comment by ghost** [comment]
Good point, 

Fixed in fbc9ac17617ef2167090d2a9ba3670b435e99518
