### ISSUE TITLE
Critical Check at the very end

### ISSUE THREAD

**Issue by ChadDa3mon** [NTTS-Innovation/GetCTS#2]
Can we perform "critical checks" at the beginning of the installation? It's quite frustrating to get through an entire process (burning up the unformatted HD and the registration key) just to have it fail. 

CRITICAL:Initiator:Release 3.10.0-1127.el7.x86_64 is too old, minimum release is at least 3.10.0-1127.8.2.el7.x86_64
CRITICAL:Initiator:Preferred solution: Make a full update by issue 'sudo yum -y update'
CRITICAL:Initiator:Failed kernel release

**Comment by ghost** [comment]
We can't run docker before it's installed. 

You will not burn the key. The preflight check will not activate the key. The key will be locked after successful initiation. You can rerun the script without any issues until it works.

**Comment by ghost** [comment]
Incorrect reference to issue from commit

**Comment by ghost** [comment]
@ChadDa3mon, did you actually "burn" you key or was that just an assumption because if that's the case then there is a bug in the backend.
